#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiii-project
  template:
    metadata:
      labels:
        app: kiii-project
    spec:
      containers:
        - name: kiii-project
          image: nikolafinkidocker/kiii-project:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgresql
            - name: DB_NAME
              value: postgres
            - name: DB_USERNAME
              value: nikola
            - name: DB_PASSWORD
              value: nikola
---
apiVersion: v1
kind: Service
metadata:
  name: kiii-project-service
spec:
  selector:
    app: kiii-project
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer