apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SitnGit/KIII_Project.git
    targetRevision: HEAD
    path: src
  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated: